#include "Adherent.h"




void Adherent::umprunterLivre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1--63c2fdde:16e1d69e291:-8000:0000000000000963 begin
{
}
// section 127-0-0-1--63c2fdde:16e1d69e291:-8000:0000000000000963 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Adherent::rendreLivre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1--63c2fdde:16e1d69e291:-8000:000000000000096B begin
{
}
// section 127-0-0-1--63c2fdde:16e1d69e291:-8000:000000000000096B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Adherent::newOperation()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1--63c2fdde:16e1d69e291:-8000:00000000000009BB begin
{
}
// section 127-0-0-1--63c2fdde:16e1d69e291:-8000:00000000000009BB end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Adherent::newOperation()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1--63c2fdde:16e1d69e291:-8000:00000000000009BD begin
{
}
// section 127-0-0-1--63c2fdde:16e1d69e291:-8000:00000000000009BD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
