#include "Bibliotheque.h"




void Bibliotheque::ajouterAdherent()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1--63c2fdde:16e1d69e291:-8000:000000000000096E begin
{
}
// section 127-0-0-1--63c2fdde:16e1d69e291:-8000:000000000000096E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Bibliotheque::enleverAdherent()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1--63c2fdde:16e1d69e291:-8000:0000000000000970 begin
{
}
// section 127-0-0-1--63c2fdde:16e1d69e291:-8000:0000000000000970 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Bibliotheque::ajouterDocument()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1--63c2fdde:16e1d69e291:-8000:0000000000000972 begin
{
}
// section 127-0-0-1--63c2fdde:16e1d69e291:-8000:0000000000000972 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
