#include "Emprunt.h"




void Emprunt::prolongerDate()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1--63c2fdde:16e1d69e291:-8000:00000000000009B2 begin
{
}
// section 127-0-0-1--63c2fdde:16e1d69e291:-8000:00000000000009B2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
