#include "livre.h"




void livre::empruntable()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-0-1--63c2fdde:16e1d69e291:-8000:00000000000009C7 begin
{
}
// section 127-0-0-1--63c2fdde:16e1d69e291:-8000:00000000000009C7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
